/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'id' : bigint,
  'content' : string,
  'isRead' : boolean,
  'orderId' : [] | [bigint],
  'timestamp' : Timestamp,
  'senderRole' : SenderRole,
  'senderId' : UserId,
  'reservationId' : [] | [bigint],
}
export interface ChatThread {
  'id' : bigint,
  'messages' : Array<ChatMessage>,
  'lastActivity' : Timestamp,
  'isOpen' : boolean,
  'orderId' : bigint,
  'customerId' : UserId,
}
export interface CustomerProfile {
  'id' : UserId,
  'dietaryPreferences' : Array<DietaryTag>,
  'name' : string,
  'favoriteItems' : Array<bigint>,
  'email' : string,
  'phone' : string,
}
export type DietaryTag = { 'chefsSpecial' : null } |
  { 'vegan' : null } |
  { 'glutenFree' : null } |
  { 'spicy' : null } |
  { 'vegetarian' : null };
export interface MenuCategory {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'emoji' : string,
}
export interface MenuItem {
  'id' : bigint,
  'categoryId' : bigint,
  'calories' : [] | [bigint],
  'name' : string,
  'tags' : Array<DietaryTag>,
  'isAvailable' : boolean,
  'description' : string,
  'isPopular' : boolean,
  'imageUrl' : string,
  'price' : bigint,
}
export interface Order {
  'id' : bigint,
  'tax' : bigint,
  'status' : OrderStatus,
  'total' : bigint,
  'createdAt' : Timestamp,
  'tableNumber' : [] | [bigint],
  'orderType' : OrderType,
  'specialInstructions' : string,
  'customerId' : UserId,
  'items' : Array<OrderItem>,
  'subtotal' : bigint,
}
export interface OrderItem {
  'specialInstructions' : string,
  'quantity' : bigint,
  'menuItemId' : bigint,
}
export type OrderStatus = { 'preparing' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null } |
  { 'ready' : null };
export type OrderType = { 'takeout' : null } |
  { 'dineIn' : null };
export interface Reservation {
  'id' : bigint,
  'customerName' : string,
  'status' : ReservationStatus,
  'specialOccasion' : [] | [string],
  'date' : string,
  'guestCount' : bigint,
  'time' : string,
  'tableId' : bigint,
  'email' : string,
  'notes' : [] | [string],
  'customerId' : UserId,
  'phone' : string,
}
export type ReservationStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export type SenderRole = { 'customer' : null } |
  { 'chef' : null };
export interface Table {
  'x' : bigint,
  'y' : bigint,
  'id' : bigint,
  'status' : TableStatus,
  'number' : bigint,
  'capacity' : bigint,
}
export type TableStatus = { 'occupied' : null } |
  { 'reserved' : null } |
  { 'available' : null } |
  { 'maintenance' : null };
export type Timestamp = bigint;
export type UserId = Principal;
export interface _SERVICE {
  'addFavoriteItem' : ActorMethod<[bigint], boolean>,
  'addMenuCategory' : ActorMethod<[string, string, string], MenuCategory>,
  'addMenuItem' : ActorMethod<
    [bigint, string, string, bigint, string, Array<DietaryTag>, [] | [bigint]],
    MenuItem
  >,
  'cancelOrder' : ActorMethod<[bigint], boolean>,
  'cancelReservation' : ActorMethod<[bigint], boolean>,
  'deleteMenuItem' : ActorMethod<[bigint], boolean>,
  'getAllCustomers' : ActorMethod<[], Array<CustomerProfile>>,
  'getAllOpenThreads' : ActorMethod<[], Array<ChatThread>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllReservations' : ActorMethod<[], Array<Reservation>>,
  'getAllTables' : ActorMethod<[], Array<Table>>,
  'getAvailableTables' : ActorMethod<[string, string, bigint], Array<Table>>,
  'getCustomerOrders' : ActorMethod<[], Array<Order>>,
  'getCustomerReservations' : ActorMethod<[], Array<Reservation>>,
  'getMenuCategories' : ActorMethod<[], Array<MenuCategory>>,
  'getMenuItem' : ActorMethod<[bigint], [] | [MenuItem]>,
  'getMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getMenuItemsByCategory' : ActorMethod<[bigint], Array<MenuItem>>,
  'getMyProfile' : ActorMethod<[], [] | [CustomerProfile]>,
  'getNewMessages' : ActorMethod<[bigint, bigint], Array<ChatMessage>>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getOrdersByStatus' : ActorMethod<[OrderStatus], Array<Order>>,
  'getReservation' : ActorMethod<[bigint], [] | [Reservation]>,
  'getThread' : ActorMethod<[bigint], [] | [ChatThread]>,
  'getThreadByOrder' : ActorMethod<[bigint], [] | [ChatThread]>,
  'makeReservation' : ActorMethod<
    [
      bigint,
      bigint,
      string,
      string,
      string,
      string,
      string,
      [] | [string],
      [] | [string],
    ],
    Reservation
  >,
  'markMessagesRead' : ActorMethod<[bigint], boolean>,
  'modifyReservation' : ActorMethod<[Reservation], boolean>,
  'placeOrder' : ActorMethod<
    [Array<OrderItem>, OrderType, string, [] | [bigint]],
    Order
  >,
  'removeFavoriteItem' : ActorMethod<[bigint], boolean>,
  'searchMenuItems' : ActorMethod<[string], Array<MenuItem>>,
  'sendChefMessage' : ActorMethod<[bigint, string], ChatMessage>,
  'sendMessage' : ActorMethod<[bigint, string], ChatMessage>,
  'toggleItemAvailability' : ActorMethod<[bigint], boolean>,
  'updateMenuItem' : ActorMethod<[MenuItem], boolean>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], boolean>,
  'updateProfile' : ActorMethod<
    [string, string, string, Array<DietaryTag>],
    CustomerProfile
  >,
  'updateReservationStatus' : ActorMethod<[bigint, ReservationStatus], boolean>,
  'updateTableStatus' : ActorMethod<[bigint, TableStatus], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];