/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MenuCategory = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'emoji' : IDL.Text,
});
export const DietaryTag = IDL.Variant({
  'chefsSpecial' : IDL.Null,
  'vegan' : IDL.Null,
  'glutenFree' : IDL.Null,
  'spicy' : IDL.Null,
  'vegetarian' : IDL.Null,
});
export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'calories' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'tags' : IDL.Vec(DietaryTag),
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'isPopular' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'price' : IDL.Nat,
});
export const UserId = IDL.Principal;
export const CustomerProfile = IDL.Record({
  'id' : UserId,
  'dietaryPreferences' : IDL.Vec(DietaryTag),
  'name' : IDL.Text,
  'favoriteItems' : IDL.Vec(IDL.Nat),
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const SenderRole = IDL.Variant({
  'customer' : IDL.Null,
  'chef' : IDL.Null,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'isRead' : IDL.Bool,
  'orderId' : IDL.Opt(IDL.Nat),
  'timestamp' : Timestamp,
  'senderRole' : SenderRole,
  'senderId' : UserId,
  'reservationId' : IDL.Opt(IDL.Nat),
});
export const ChatThread = IDL.Record({
  'id' : IDL.Nat,
  'messages' : IDL.Vec(ChatMessage),
  'lastActivity' : Timestamp,
  'isOpen' : IDL.Bool,
  'orderId' : IDL.Nat,
  'customerId' : UserId,
});
export const OrderStatus = IDL.Variant({
  'preparing' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
  'ready' : IDL.Null,
});
export const OrderType = IDL.Variant({
  'takeout' : IDL.Null,
  'dineIn' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'specialInstructions' : IDL.Text,
  'quantity' : IDL.Nat,
  'menuItemId' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'tax' : IDL.Nat,
  'status' : OrderStatus,
  'total' : IDL.Nat,
  'createdAt' : Timestamp,
  'tableNumber' : IDL.Opt(IDL.Nat),
  'orderType' : OrderType,
  'specialInstructions' : IDL.Text,
  'customerId' : UserId,
  'items' : IDL.Vec(OrderItem),
  'subtotal' : IDL.Nat,
});
export const ReservationStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Reservation = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : ReservationStatus,
  'specialOccasion' : IDL.Opt(IDL.Text),
  'date' : IDL.Text,
  'guestCount' : IDL.Nat,
  'time' : IDL.Text,
  'tableId' : IDL.Nat,
  'email' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'customerId' : UserId,
  'phone' : IDL.Text,
});
export const TableStatus = IDL.Variant({
  'occupied' : IDL.Null,
  'reserved' : IDL.Null,
  'available' : IDL.Null,
  'maintenance' : IDL.Null,
});
export const Table = IDL.Record({
  'x' : IDL.Nat,
  'y' : IDL.Nat,
  'id' : IDL.Nat,
  'status' : TableStatus,
  'number' : IDL.Nat,
  'capacity' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addFavoriteItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'addMenuCategory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [MenuCategory],
      [],
    ),
  'addMenuItem' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Vec(DietaryTag),
        IDL.Opt(IDL.Nat),
      ],
      [MenuItem],
      [],
    ),
  'cancelOrder' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'cancelReservation' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteMenuItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(CustomerProfile)], []),
  'getAllOpenThreads' : IDL.Func([], [IDL.Vec(ChatThread)], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], []),
  'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], []),
  'getAllTables' : IDL.Func([], [IDL.Vec(Table)], ['query']),
  'getAvailableTables' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Vec(Table)],
      ['query'],
    ),
  'getCustomerOrders' : IDL.Func([], [IDL.Vec(Order)], []),
  'getCustomerReservations' : IDL.Func([], [IDL.Vec(Reservation)], []),
  'getMenuCategories' : IDL.Func([], [IDL.Vec(MenuCategory)], ['query']),
  'getMenuItem' : IDL.Func([IDL.Nat], [IDL.Opt(MenuItem)], ['query']),
  'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getMenuItemsByCategory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'getMyProfile' : IDL.Func([], [IDL.Opt(CustomerProfile)], []),
  'getNewMessages' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getOrdersByStatus' : IDL.Func([OrderStatus], [IDL.Vec(Order)], []),
  'getReservation' : IDL.Func([IDL.Nat], [IDL.Opt(Reservation)], ['query']),
  'getThread' : IDL.Func([IDL.Nat], [IDL.Opt(ChatThread)], ['query']),
  'getThreadByOrder' : IDL.Func([IDL.Nat], [IDL.Opt(ChatThread)], ['query']),
  'makeReservation' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [Reservation],
      [],
    ),
  'markMessagesRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'modifyReservation' : IDL.Func([Reservation], [IDL.Bool], []),
  'placeOrder' : IDL.Func(
      [IDL.Vec(OrderItem), OrderType, IDL.Text, IDL.Opt(IDL.Nat)],
      [Order],
      [],
    ),
  'removeFavoriteItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'searchMenuItems' : IDL.Func([IDL.Text], [IDL.Vec(MenuItem)], ['query']),
  'sendChefMessage' : IDL.Func([IDL.Nat, IDL.Text], [ChatMessage], []),
  'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [ChatMessage], []),
  'toggleItemAvailability' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'updateMenuItem' : IDL.Func([MenuItem], [IDL.Bool], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [IDL.Bool], []),
  'updateProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(DietaryTag)],
      [CustomerProfile],
      [],
    ),
  'updateReservationStatus' : IDL.Func(
      [IDL.Nat, ReservationStatus],
      [IDL.Bool],
      [],
    ),
  'updateTableStatus' : IDL.Func([IDL.Nat, TableStatus], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MenuCategory = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'emoji' : IDL.Text,
  });
  const DietaryTag = IDL.Variant({
    'chefsSpecial' : IDL.Null,
    'vegan' : IDL.Null,
    'glutenFree' : IDL.Null,
    'spicy' : IDL.Null,
    'vegetarian' : IDL.Null,
  });
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'calories' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'tags' : IDL.Vec(DietaryTag),
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'isPopular' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'price' : IDL.Nat,
  });
  const UserId = IDL.Principal;
  const CustomerProfile = IDL.Record({
    'id' : UserId,
    'dietaryPreferences' : IDL.Vec(DietaryTag),
    'name' : IDL.Text,
    'favoriteItems' : IDL.Vec(IDL.Nat),
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const SenderRole = IDL.Variant({ 'customer' : IDL.Null, 'chef' : IDL.Null });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'isRead' : IDL.Bool,
    'orderId' : IDL.Opt(IDL.Nat),
    'timestamp' : Timestamp,
    'senderRole' : SenderRole,
    'senderId' : UserId,
    'reservationId' : IDL.Opt(IDL.Nat),
  });
  const ChatThread = IDL.Record({
    'id' : IDL.Nat,
    'messages' : IDL.Vec(ChatMessage),
    'lastActivity' : Timestamp,
    'isOpen' : IDL.Bool,
    'orderId' : IDL.Nat,
    'customerId' : UserId,
  });
  const OrderStatus = IDL.Variant({
    'preparing' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
    'ready' : IDL.Null,
  });
  const OrderType = IDL.Variant({ 'takeout' : IDL.Null, 'dineIn' : IDL.Null });
  const OrderItem = IDL.Record({
    'specialInstructions' : IDL.Text,
    'quantity' : IDL.Nat,
    'menuItemId' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'tax' : IDL.Nat,
    'status' : OrderStatus,
    'total' : IDL.Nat,
    'createdAt' : Timestamp,
    'tableNumber' : IDL.Opt(IDL.Nat),
    'orderType' : OrderType,
    'specialInstructions' : IDL.Text,
    'customerId' : UserId,
    'items' : IDL.Vec(OrderItem),
    'subtotal' : IDL.Nat,
  });
  const ReservationStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Reservation = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : ReservationStatus,
    'specialOccasion' : IDL.Opt(IDL.Text),
    'date' : IDL.Text,
    'guestCount' : IDL.Nat,
    'time' : IDL.Text,
    'tableId' : IDL.Nat,
    'email' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'customerId' : UserId,
    'phone' : IDL.Text,
  });
  const TableStatus = IDL.Variant({
    'occupied' : IDL.Null,
    'reserved' : IDL.Null,
    'available' : IDL.Null,
    'maintenance' : IDL.Null,
  });
  const Table = IDL.Record({
    'x' : IDL.Nat,
    'y' : IDL.Nat,
    'id' : IDL.Nat,
    'status' : TableStatus,
    'number' : IDL.Nat,
    'capacity' : IDL.Nat,
  });
  
  return IDL.Service({
    'addFavoriteItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'addMenuCategory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [MenuCategory],
        [],
      ),
    'addMenuItem' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(DietaryTag),
          IDL.Opt(IDL.Nat),
        ],
        [MenuItem],
        [],
      ),
    'cancelOrder' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'cancelReservation' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteMenuItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(CustomerProfile)], []),
    'getAllOpenThreads' : IDL.Func([], [IDL.Vec(ChatThread)], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], []),
    'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], []),
    'getAllTables' : IDL.Func([], [IDL.Vec(Table)], ['query']),
    'getAvailableTables' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Vec(Table)],
        ['query'],
      ),
    'getCustomerOrders' : IDL.Func([], [IDL.Vec(Order)], []),
    'getCustomerReservations' : IDL.Func([], [IDL.Vec(Reservation)], []),
    'getMenuCategories' : IDL.Func([], [IDL.Vec(MenuCategory)], ['query']),
    'getMenuItem' : IDL.Func([IDL.Nat], [IDL.Opt(MenuItem)], ['query']),
    'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getMenuItemsByCategory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([], [IDL.Opt(CustomerProfile)], []),
    'getNewMessages' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getOrdersByStatus' : IDL.Func([OrderStatus], [IDL.Vec(Order)], []),
    'getReservation' : IDL.Func([IDL.Nat], [IDL.Opt(Reservation)], ['query']),
    'getThread' : IDL.Func([IDL.Nat], [IDL.Opt(ChatThread)], ['query']),
    'getThreadByOrder' : IDL.Func([IDL.Nat], [IDL.Opt(ChatThread)], ['query']),
    'makeReservation' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [Reservation],
        [],
      ),
    'markMessagesRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'modifyReservation' : IDL.Func([Reservation], [IDL.Bool], []),
    'placeOrder' : IDL.Func(
        [IDL.Vec(OrderItem), OrderType, IDL.Text, IDL.Opt(IDL.Nat)],
        [Order],
        [],
      ),
    'removeFavoriteItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'searchMenuItems' : IDL.Func([IDL.Text], [IDL.Vec(MenuItem)], ['query']),
    'sendChefMessage' : IDL.Func([IDL.Nat, IDL.Text], [ChatMessage], []),
    'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [ChatMessage], []),
    'toggleItemAvailability' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'updateMenuItem' : IDL.Func([MenuItem], [IDL.Bool], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [IDL.Bool], []),
    'updateProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(DietaryTag)],
        [CustomerProfile],
        [],
      ),
    'updateReservationStatus' : IDL.Func(
        [IDL.Nat, ReservationStatus],
        [IDL.Bool],
        [],
      ),
    'updateTableStatus' : IDL.Func([IDL.Nat, TableStatus], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };