/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface MenuCategory {
    id: bigint;
    name: string;
    description: string;
    emoji: string;
}
export interface OrderItem {
    specialInstructions: string;
    quantity: bigint;
    menuItemId: bigint;
}
export interface Reservation {
    id: bigint;
    customerName: string;
    status: ReservationStatus;
    specialOccasion?: string;
    date: string;
    guestCount: bigint;
    time: string;
    tableId: bigint;
    email: string;
    notes?: string;
    customerId: UserId;
    phone: string;
}
export interface CustomerProfile {
    id: UserId;
    dietaryPreferences: Array<DietaryTag>;
    name: string;
    favoriteItems: Array<bigint>;
    email: string;
    phone: string;
}
export interface Order {
    id: bigint;
    tax: bigint;
    status: OrderStatus;
    total: bigint;
    createdAt: Timestamp;
    tableNumber?: bigint;
    orderType: OrderType;
    specialInstructions: string;
    customerId: UserId;
    items: Array<OrderItem>;
    subtotal: bigint;
}
export type UserId = Principal;
export interface MenuItem {
    id: bigint;
    categoryId: bigint;
    calories?: bigint;
    name: string;
    tags: Array<DietaryTag>;
    isAvailable: boolean;
    description: string;
    isPopular: boolean;
    imageUrl: string;
    price: bigint;
}
export interface ChatThread {
    id: bigint;
    messages: Array<ChatMessage>;
    lastActivity: Timestamp;
    isOpen: boolean;
    orderId: bigint;
    customerId: UserId;
}
export interface Table {
    x: bigint;
    y: bigint;
    id: bigint;
    status: TableStatus;
    number: bigint;
    capacity: bigint;
}
export interface ChatMessage {
    id: bigint;
    content: string;
    isRead: boolean;
    orderId?: bigint;
    timestamp: Timestamp;
    senderRole: SenderRole;
    senderId: UserId;
    reservationId?: bigint;
}
export enum DietaryTag {
    chefsSpecial = "chefsSpecial",
    vegan = "vegan",
    glutenFree = "glutenFree",
    spicy = "spicy",
    vegetarian = "vegetarian"
}
export enum OrderStatus {
    preparing = "preparing",
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    confirmed = "confirmed",
    ready = "ready"
}
export enum OrderType {
    takeout = "takeout",
    dineIn = "dineIn"
}
export enum ReservationStatus {
    cancelled = "cancelled",
    pending = "pending",
    confirmed = "confirmed"
}
export enum SenderRole {
    customer = "customer",
    chef = "chef"
}
export enum TableStatus {
    occupied = "occupied",
    reserved = "reserved",
    available = "available",
    maintenance = "maintenance"
}
export interface backendInterface {
    addFavoriteItem(menuItemId: bigint): Promise<boolean>;
    addMenuCategory(name: string, description: string, emoji: string): Promise<MenuCategory>;
    addMenuItem(categoryId: bigint, name: string, description: string, price: bigint, imageUrl: string, tags: Array<DietaryTag>, calories: bigint | null): Promise<MenuItem>;
    cancelOrder(id: bigint): Promise<boolean>;
    cancelReservation(id: bigint): Promise<boolean>;
    deleteMenuItem(id: bigint): Promise<boolean>;
    getAllCustomers(): Promise<Array<CustomerProfile>>;
    getAllOpenThreads(): Promise<Array<ChatThread>>;
    getAllOrders(): Promise<Array<Order>>;
    getAllReservations(): Promise<Array<Reservation>>;
    getAllTables(): Promise<Array<Table>>;
    getAvailableTables(date: string, time: string, guestCount: bigint): Promise<Array<Table>>;
    getCustomerOrders(): Promise<Array<Order>>;
    getCustomerReservations(): Promise<Array<Reservation>>;
    getMenuCategories(): Promise<Array<MenuCategory>>;
    getMenuItem(id: bigint): Promise<MenuItem | null>;
    getMenuItems(): Promise<Array<MenuItem>>;
    getMenuItemsByCategory(categoryId: bigint): Promise<Array<MenuItem>>;
    getMyProfile(): Promise<CustomerProfile | null>;
    getNewMessages(threadId: bigint, lastMessageId: bigint): Promise<Array<ChatMessage>>;
    getOrder(id: bigint): Promise<Order | null>;
    getOrdersByStatus(status: OrderStatus): Promise<Array<Order>>;
    getReservation(id: bigint): Promise<Reservation | null>;
    getThread(threadId: bigint): Promise<ChatThread | null>;
    getThreadByOrder(orderId: bigint): Promise<ChatThread | null>;
    makeReservation(tableId: bigint, guestCount: bigint, date: string, time: string, customerName: string, phone: string, email: string, specialOccasion: string | null, notes: string | null): Promise<Reservation>;
    markMessagesRead(threadId: bigint): Promise<boolean>;
    modifyReservation(updated: Reservation): Promise<boolean>;
    placeOrder(items: Array<OrderItem>, orderType: OrderType, specialInstructions: string, tableNumber: bigint | null): Promise<Order>;
    removeFavoriteItem(menuItemId: bigint): Promise<boolean>;
    searchMenuItems(searchTerm: string): Promise<Array<MenuItem>>;
    sendChefMessage(orderId: bigint, content: string): Promise<ChatMessage>;
    sendMessage(orderId: bigint, content: string): Promise<ChatMessage>;
    toggleItemAvailability(id: bigint): Promise<boolean>;
    updateMenuItem(item: MenuItem): Promise<boolean>;
    updateOrderStatus(id: bigint, status: OrderStatus): Promise<boolean>;
    updateProfile(name: string, phone: string, email: string, dietaryPreferences: Array<DietaryTag>): Promise<CustomerProfile>;
    updateReservationStatus(id: bigint, status: ReservationStatus): Promise<boolean>;
    updateTableStatus(id: bigint, status: TableStatus): Promise<boolean>;
}
import type { ChatMessage as _ChatMessage, ChatThread as _ChatThread, CustomerProfile as _CustomerProfile, DietaryTag as _DietaryTag, MenuItem as _MenuItem, Order as _Order, OrderItem as _OrderItem, OrderStatus as _OrderStatus, OrderType as _OrderType, Reservation as _Reservation, ReservationStatus as _ReservationStatus, SenderRole as _SenderRole, Table as _Table, TableStatus as _TableStatus, Timestamp as _Timestamp, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addFavoriteItem(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addFavoriteItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFavoriteItem(arg0);
            return result;
        }
    }
    async addMenuCategory(arg0: string, arg1: string, arg2: string): Promise<MenuCategory> {
        if (this.processError) {
            try {
                const result = await this.actor.addMenuCategory(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMenuCategory(arg0, arg1, arg2);
            return result;
        }
    }
    async addMenuItem(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: Array<DietaryTag>, arg6: bigint | null): Promise<MenuItem> {
        if (this.processError) {
            try {
                const result = await this.actor.addMenuItem(arg0, arg1, arg2, arg3, arg4, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg6));
                return from_candid_MenuItem_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMenuItem(arg0, arg1, arg2, arg3, arg4, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg6));
            return from_candid_MenuItem_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async cancelOrder(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelOrder(arg0);
            return result;
        }
    }
    async cancelReservation(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelReservation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelReservation(arg0);
            return result;
        }
    }
    async deleteMenuItem(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMenuItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMenuItem(arg0);
            return result;
        }
    }
    async getAllCustomers(): Promise<Array<CustomerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomers();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomers();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllOpenThreads(): Promise<Array<ChatThread>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOpenThreads();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOpenThreads();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllReservations(): Promise<Array<Reservation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReservations();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReservations();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTables(): Promise<Array<Table>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTables();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTables();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableTables(arg0: string, arg1: string, arg2: bigint): Promise<Array<Table>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableTables(arg0, arg1, arg2);
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableTables(arg0, arg1, arg2);
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerOrders();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerOrders();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerReservations(): Promise<Array<Reservation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerReservations();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerReservations();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMenuCategories(): Promise<Array<MenuCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuCategories();
            return result;
        }
    }
    async getMenuItem(arg0: bigint): Promise<MenuItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItem(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItem(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMenuItems(): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItems();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItems();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMenuItemsByCategory(arg0: bigint): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItemsByCategory(arg0);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItemsByCategory(arg0);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<CustomerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNewMessages(arg0: bigint, arg1: bigint): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewMessages(arg0, arg1);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewMessages(arg0, arg1);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: bigint): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrdersByStatus(arg0: OrderStatus): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByStatus(to_candid_OrderStatus_n44(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByStatus(to_candid_OrderStatus_n44(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReservation(arg0: bigint): Promise<Reservation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReservation(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReservation(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getThread(arg0: bigint): Promise<ChatThread | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getThread(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getThread(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getThreadByOrder(arg0: bigint): Promise<ChatThread | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getThreadByOrder(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getThreadByOrder(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async makeReservation(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string | null, arg8: string | null): Promise<Reservation> {
        if (this.processError) {
            try {
                const result = await this.actor.makeReservation(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n48(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n48(this._uploadFile, this._downloadFile, arg8));
                return from_candid_Reservation_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.makeReservation(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n48(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n48(this._uploadFile, this._downloadFile, arg8));
            return from_candid_Reservation_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async markMessagesRead(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markMessagesRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMessagesRead(arg0);
            return result;
        }
    }
    async modifyReservation(arg0: Reservation): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.modifyReservation(to_candid_Reservation_n49(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.modifyReservation(to_candid_Reservation_n49(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async placeOrder(arg0: Array<OrderItem>, arg1: OrderType, arg2: string, arg3: bigint | null): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0, to_candid_OrderType_n53(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Order_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0, to_candid_OrderType_n53(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Order_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeFavoriteItem(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFavoriteItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFavoriteItem(arg0);
            return result;
        }
    }
    async searchMenuItems(arg0: string): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchMenuItems(arg0);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchMenuItems(arg0);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendChefMessage(arg0: bigint, arg1: string): Promise<ChatMessage> {
        if (this.processError) {
            try {
                const result = await this.actor.sendChefMessage(arg0, arg1);
                return from_candid_ChatMessage_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendChefMessage(arg0, arg1);
            return from_candid_ChatMessage_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendMessage(arg0: bigint, arg1: string): Promise<ChatMessage> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return from_candid_ChatMessage_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return from_candid_ChatMessage_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleItemAvailability(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleItemAvailability(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleItemAvailability(arg0);
            return result;
        }
    }
    async updateMenuItem(arg0: MenuItem): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMenuItem(to_candid_MenuItem_n55(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMenuItem(to_candid_MenuItem_n55(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateOrderStatus(arg0: bigint, arg1: OrderStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n44(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n44(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProfile(arg0: string, arg1: string, arg2: string, arg3: Array<DietaryTag>): Promise<CustomerProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1, arg2, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg3));
                return from_candid_CustomerProfile_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1, arg2, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg3));
            return from_candid_CustomerProfile_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateReservationStatus(arg0: bigint, arg1: ReservationStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReservationStatus(arg0, to_candid_ReservationStatus_n51(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReservationStatus(arg0, to_candid_ReservationStatus_n51(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTableStatus(arg0: bigint, arg1: TableStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTableStatus(arg0, to_candid_TableStatus_n57(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTableStatus(arg0, to_candid_TableStatus_n57(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ChatMessage_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatMessage): ChatMessage {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_ChatThread_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatThread): ChatThread {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_CustomerProfile_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomerProfile): CustomerProfile {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_DietaryTag_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DietaryTag): DietaryTag {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_MenuItem_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MenuItem): MenuItem {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_OrderType_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderType): OrderType {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_ReservationStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReservationStatus): ReservationStatus {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_Reservation_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Reservation): Reservation {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_SenderRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SenderRole): SenderRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_TableStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TableStatus): TableStatus {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Table_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Table): Table {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MenuItem]): MenuItem | null {
    return value.length === 0 ? null : from_candid_MenuItem_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CustomerProfile]): CustomerProfile | null {
    return value.length === 0 ? null : from_candid_CustomerProfile_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Reservation]): Reservation | null {
    return value.length === 0 ? null : from_candid_Reservation_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ChatThread]): ChatThread | null {
    return value.length === 0 ? null : from_candid_ChatThread_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    dietaryPreferences: Array<_DietaryTag>;
    name: string;
    favoriteItems: Array<bigint>;
    email: string;
    phone: string;
}): {
    id: UserId;
    dietaryPreferences: Array<DietaryTag>;
    name: string;
    favoriteItems: Array<bigint>;
    email: string;
    phone: string;
} {
    return {
        id: value.id,
        dietaryPreferences: from_candid_vec_n8(_uploadFile, _downloadFile, value.dietaryPreferences),
        name: value.name,
        favoriteItems: value.favoriteItems,
        email: value.email,
        phone: value.phone
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    messages: Array<_ChatMessage>;
    lastActivity: _Timestamp;
    isOpen: boolean;
    orderId: bigint;
    customerId: _UserId;
}): {
    id: bigint;
    messages: Array<ChatMessage>;
    lastActivity: Timestamp;
    isOpen: boolean;
    orderId: bigint;
    customerId: UserId;
} {
    return {
        id: value.id,
        messages: from_candid_vec_n17(_uploadFile, _downloadFile, value.messages),
        lastActivity: value.lastActivity,
        isOpen: value.isOpen,
        orderId: value.orderId,
        customerId: value.customerId
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: string;
    isRead: boolean;
    orderId: [] | [bigint];
    timestamp: _Timestamp;
    senderRole: _SenderRole;
    senderId: _UserId;
    reservationId: [] | [bigint];
}): {
    id: bigint;
    content: string;
    isRead: boolean;
    orderId?: bigint;
    timestamp: Timestamp;
    senderRole: SenderRole;
    senderId: UserId;
    reservationId?: bigint;
} {
    return {
        id: value.id,
        content: value.content,
        isRead: value.isRead,
        orderId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.orderId)),
        timestamp: value.timestamp,
        senderRole: from_candid_SenderRole_n20(_uploadFile, _downloadFile, value.senderRole),
        senderId: value.senderId,
        reservationId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.reservationId))
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    tax: bigint;
    status: _OrderStatus;
    total: bigint;
    createdAt: _Timestamp;
    tableNumber: [] | [bigint];
    orderType: _OrderType;
    specialInstructions: string;
    customerId: _UserId;
    items: Array<_OrderItem>;
    subtotal: bigint;
}): {
    id: bigint;
    tax: bigint;
    status: OrderStatus;
    total: bigint;
    createdAt: Timestamp;
    tableNumber?: bigint;
    orderType: OrderType;
    specialInstructions: string;
    customerId: UserId;
    items: Array<OrderItem>;
    subtotal: bigint;
} {
    return {
        id: value.id,
        tax: value.tax,
        status: from_candid_OrderStatus_n25(_uploadFile, _downloadFile, value.status),
        total: value.total,
        createdAt: value.createdAt,
        tableNumber: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.tableNumber)),
        orderType: from_candid_OrderType_n27(_uploadFile, _downloadFile, value.orderType),
        specialInstructions: value.specialInstructions,
        customerId: value.customerId,
        items: value.items,
        subtotal: value.subtotal
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    status: _ReservationStatus;
    specialOccasion: [] | [string];
    date: string;
    guestCount: bigint;
    time: string;
    tableId: bigint;
    email: string;
    notes: [] | [string];
    customerId: _UserId;
    phone: string;
}): {
    id: bigint;
    customerName: string;
    status: ReservationStatus;
    specialOccasion?: string;
    date: string;
    guestCount: bigint;
    time: string;
    tableId: bigint;
    email: string;
    notes?: string;
    customerId: UserId;
    phone: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_ReservationStatus_n32(_uploadFile, _downloadFile, value.status),
        specialOccasion: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.specialOccasion)),
        date: value.date,
        guestCount: value.guestCount,
        time: value.time,
        tableId: value.tableId,
        email: value.email,
        notes: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.notes)),
        customerId: value.customerId,
        phone: value.phone
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    x: bigint;
    y: bigint;
    id: bigint;
    status: _TableStatus;
    number: bigint;
    capacity: bigint;
}): {
    x: bigint;
    y: bigint;
    id: bigint;
    status: TableStatus;
    number: bigint;
    capacity: bigint;
} {
    return {
        x: value.x,
        y: value.y,
        id: value.id,
        status: from_candid_TableStatus_n38(_uploadFile, _downloadFile, value.status),
        number: value.number,
        capacity: value.capacity
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    categoryId: bigint;
    calories: [] | [bigint];
    name: string;
    tags: Array<_DietaryTag>;
    isAvailable: boolean;
    description: string;
    isPopular: boolean;
    imageUrl: string;
    price: bigint;
}): {
    id: bigint;
    categoryId: bigint;
    calories?: bigint;
    name: string;
    tags: Array<DietaryTag>;
    isAvailable: boolean;
    description: string;
    isPopular: boolean;
    imageUrl: string;
    price: bigint;
} {
    return {
        id: value.id,
        categoryId: value.categoryId,
        calories: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.calories)),
        name: value.name,
        tags: from_candid_vec_n8(_uploadFile, _downloadFile, value.tags),
        isAvailable: value.isAvailable,
        description: value.description,
        isPopular: value.isPopular,
        imageUrl: value.imageUrl,
        price: value.price
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    chefsSpecial: null;
} | {
    vegan: null;
} | {
    glutenFree: null;
} | {
    spicy: null;
} | {
    vegetarian: null;
}): DietaryTag {
    return "chefsSpecial" in value ? DietaryTag.chefsSpecial : "vegan" in value ? DietaryTag.vegan : "glutenFree" in value ? DietaryTag.glutenFree : "spicy" in value ? DietaryTag.spicy : "vegetarian" in value ? DietaryTag.vegetarian : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customer: null;
} | {
    chef: null;
}): SenderRole {
    return "customer" in value ? SenderRole.customer : "chef" in value ? SenderRole.chef : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    preparing: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
} | {
    ready: null;
}): OrderStatus {
    return "preparing" in value ? OrderStatus.preparing : "cancelled" in value ? OrderStatus.cancelled : "pending" in value ? OrderStatus.pending : "completed" in value ? OrderStatus.completed : "confirmed" in value ? OrderStatus.confirmed : "ready" in value ? OrderStatus.ready : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    takeout: null;
} | {
    dineIn: null;
}): OrderType {
    return "takeout" in value ? OrderType.takeout : "dineIn" in value ? OrderType.dineIn : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
}): ReservationStatus {
    return "cancelled" in value ? ReservationStatus.cancelled : "pending" in value ? ReservationStatus.pending : "confirmed" in value ? ReservationStatus.confirmed : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    occupied: null;
} | {
    reserved: null;
} | {
    available: null;
} | {
    maintenance: null;
}): TableStatus {
    return "occupied" in value ? TableStatus.occupied : "reserved" in value ? TableStatus.reserved : "available" in value ? TableStatus.available : "maintenance" in value ? TableStatus.maintenance : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CustomerProfile>): Array<CustomerProfile> {
    return value.map((x)=>from_candid_CustomerProfile_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChatThread>): Array<ChatThread> {
    return value.map((x)=>from_candid_ChatThread_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChatMessage>): Array<ChatMessage> {
    return value.map((x)=>from_candid_ChatMessage_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Reservation>): Array<Reservation> {
    return value.map((x)=>from_candid_Reservation_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Table>): Array<Table> {
    return value.map((x)=>from_candid_Table_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MenuItem>): Array<MenuItem> {
    return value.map((x)=>from_candid_MenuItem_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DietaryTag>): Array<DietaryTag> {
    return value.map((x)=>from_candid_DietaryTag_n9(_uploadFile, _downloadFile, x));
}
function to_candid_DietaryTag_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DietaryTag): _DietaryTag {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_MenuItem_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MenuItem): _MenuItem {
    return to_candid_record_n56(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function to_candid_OrderType_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderType): _OrderType {
    return to_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function to_candid_ReservationStatus_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReservationStatus): _ReservationStatus {
    return to_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function to_candid_Reservation_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Reservation): _Reservation {
    return to_candid_record_n50(_uploadFile, _downloadFile, value);
}
function to_candid_TableStatus_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TableStatus): _TableStatus {
    return to_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    status: ReservationStatus;
    specialOccasion?: string;
    date: string;
    guestCount: bigint;
    time: string;
    tableId: bigint;
    email: string;
    notes?: string;
    customerId: UserId;
    phone: string;
}): {
    id: bigint;
    customerName: string;
    status: _ReservationStatus;
    specialOccasion: [] | [string];
    date: string;
    guestCount: bigint;
    time: string;
    tableId: bigint;
    email: string;
    notes: [] | [string];
    customerId: _UserId;
    phone: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: to_candid_ReservationStatus_n51(_uploadFile, _downloadFile, value.status),
        specialOccasion: value.specialOccasion ? candid_some(value.specialOccasion) : candid_none(),
        date: value.date,
        guestCount: value.guestCount,
        time: value.time,
        tableId: value.tableId,
        email: value.email,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        customerId: value.customerId,
        phone: value.phone
    };
}
function to_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    categoryId: bigint;
    calories?: bigint;
    name: string;
    tags: Array<DietaryTag>;
    isAvailable: boolean;
    description: string;
    isPopular: boolean;
    imageUrl: string;
    price: bigint;
}): {
    id: bigint;
    categoryId: bigint;
    calories: [] | [bigint];
    name: string;
    tags: Array<_DietaryTag>;
    isAvailable: boolean;
    description: string;
    isPopular: boolean;
    imageUrl: string;
    price: bigint;
} {
    return {
        id: value.id,
        categoryId: value.categoryId,
        calories: value.calories ? candid_some(value.calories) : candid_none(),
        name: value.name,
        tags: to_candid_vec_n1(_uploadFile, _downloadFile, value.tags),
        isAvailable: value.isAvailable,
        description: value.description,
        isPopular: value.isPopular,
        imageUrl: value.imageUrl,
        price: value.price
    };
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DietaryTag): {
    chefsSpecial: null;
} | {
    vegan: null;
} | {
    glutenFree: null;
} | {
    spicy: null;
} | {
    vegetarian: null;
} {
    return value == DietaryTag.chefsSpecial ? {
        chefsSpecial: null
    } : value == DietaryTag.vegan ? {
        vegan: null
    } : value == DietaryTag.glutenFree ? {
        glutenFree: null
    } : value == DietaryTag.spicy ? {
        spicy: null
    } : value == DietaryTag.vegetarian ? {
        vegetarian: null
    } : value;
}
function to_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    preparing: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
} | {
    ready: null;
} {
    return value == OrderStatus.preparing ? {
        preparing: null
    } : value == OrderStatus.cancelled ? {
        cancelled: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.completed ? {
        completed: null
    } : value == OrderStatus.confirmed ? {
        confirmed: null
    } : value == OrderStatus.ready ? {
        ready: null
    } : value;
}
function to_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReservationStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
} {
    return value == ReservationStatus.cancelled ? {
        cancelled: null
    } : value == ReservationStatus.pending ? {
        pending: null
    } : value == ReservationStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderType): {
    takeout: null;
} | {
    dineIn: null;
} {
    return value == OrderType.takeout ? {
        takeout: null
    } : value == OrderType.dineIn ? {
        dineIn: null
    } : value;
}
function to_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TableStatus): {
    occupied: null;
} | {
    reserved: null;
} | {
    available: null;
} | {
    maintenance: null;
} {
    return value == TableStatus.occupied ? {
        occupied: null
    } : value == TableStatus.reserved ? {
        reserved: null
    } : value == TableStatus.available ? {
        available: null
    } : value == TableStatus.maintenance ? {
        maintenance: null
    } : value;
}
function to_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<DietaryTag>): Array<_DietaryTag> {
    return value.map((x)=>to_candid_DietaryTag_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
